waypoints:
- latitude: 38.161456561759785
  longitude: -122.45460667598131
  yaw: -0.04259982770796795
- latitude: 38.161453322394934
  longitude: -122.45459950955255
  yaw: -0.5889892736861153
- latitude: 38.161446329381675
  longitude: -122.45458793008707
  yaw: -0.6834014058623078
- latitude: 38.16144048788813
  longitude: -122.45457891354664
  yaw: -0.7497921633304699
- latitude: 38.16143423379251
  longitude: -122.45457008766677
  yaw: -0.6888817229744723
- latitude: 38.1614285521
  longitude: -122.45456119910482
  yaw: -0.7222502705001931
- latitude: 38.1614239674414
  longitude: -122.45455439988297
  yaw: -0.6428648520302843
- latitude: 38.16141852881577
  longitude: -122.45454508571245
  yaw: -0.647770626507372
- latitude: 38.16141290872552
  longitude: -122.45453556087648
  yaw: -0.6846941366946765
- latitude: 38.16140859477615
  longitude: -122.45452883432273
  yaw: -0.6934104516176538
- latitude: 38.16140118664066
  longitude: -122.4545177068959
  yaw: -0.6488160835343354
- latitude: 38.1613970066073
  longitude: -122.45451065921456
  yaw: -0.654760184142864
- latitude: 38.16139305687418
  longitude: -122.45450330720668
  yaw: -0.6721999936914465
- latitude: 38.1613870745243
  longitude: -122.45449445405072
  yaw: -0.6737071752984337
- latitude: 38.16138142922007
  longitude: -122.45448506005117
  yaw: -0.6487208433611358
- latitude: 38.161377307077
  longitude: -122.4544780882952
  yaw: -0.6882269177557773
- latitude: 38.161371810195476
  longitude: -122.45446885539837
  yaw: -0.6607398142799089
- latitude: 38.16136739317103
  longitude: -122.4544618820964
  yaw: -0.6481552066670238
- latitude: 38.16136213362256
  longitude: -122.4544524814874
  yaw: -0.6612108273447133
- latitude: 38.16135625859591
  longitude: -122.45444324694735
  yaw: -0.6676571368733567
- latitude: 38.16135343793828
  longitude: -122.45443853266634
  yaw: -0.6823029097470585
- latitude: 38.16134909982907
  longitude: -122.4544319391609
  yaw: -0.662185825715516
- latitude: 38.16134670007676
  longitude: -122.45442775796889
  yaw: -0.6743840233995029
